- name: Run tests
  env:
      HOST: ${{ secrets.HOST }}
      PORT: ${{ secrets.PORT }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
  run: |
    ${{ workspaceFolder }}/manage.py
    args: ["runserver"]
